# Netlify Configuration File

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache/**,.next/cache/**"
  SECRETS_SCAN_OMIT_KEYS = "AXIOM_TOKEN"

[[headers]]
  for = "/*"
  [headers.values]
    Netlify-Vary = "query"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/api/*"
  [headers.values]
    Netlify-Vary = "query"
    Cache-Control = "public, max-age=3600, s-maxage=86400, stale-while-revalidate=604800"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


[[redirects]]
  from = "https://zone45678analysis.netlify.app/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://zone45678analysis.netlify.app/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://4567.rsamdio.org/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://4567.rsamdio.org/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://45678.rsamdio.org/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://45678.rsamdio.org/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true
