# Netlify Configuration File

[[redirects]]
  from = "https://zone45678analysis.netlify.app/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://zone45678analysis.netlify.app/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://4567.rsamdio.org/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://4567.rsamdio.org/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://45678.rsamdio.org/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://45678.rsamdio.org/*"
  to = "https://insights.rsamdio.org/:splat"
  status = 301
  force = true
